version: "3.2"
services:
  nginx-wrapper:
    image: cbioportal-cloud-nginx-wrapper:latest
    build:
      context: services/nginx-wrapper
    ports: #NGINX_WRAPPER
    #- "${NGINX_WRAPPER_PORT_HTTP}:80"
    #- "${NGINX_WRAPPER_PORT_HTTPS}:443"
    - "80:80"
    - "443:443"
    - "8080:8080"
    - "8443:8443"
    volumes:
    - type: bind
      source: ./services/nginx-wrapper/nginx.conf
      target: /etc/nginx/conf.d/default.conf
      read_only: true
    - type: bind
      source: ./mountpoints/nginx-wrapper/cert.crt
      target: /etc/nginx/cert.crt
      read_only: true
    - type: bind
      source: ./mountpoints/nginx-wrapper/cert.key
      target: /etc/nginx/cert.key
      read_only: true
    - type: bind
      source: ./mountpoints/dashboard/
      target: /etc/nginx/html/dashboard
      read_only: true
    - type: bind
      source: ./mountpoints/host/
      target: /host
      read_only: true
    depends_on:
    - cbioportal
    links:
    - cbioportal
    networks:
    - cbio-bridge
  cbioportal:
    image: cbioportal-cloud:latest
    build:
      context: services/cbioportal
      args:
        BRANCH: ${CBIOPORTAL_BRANCH}
        SEED_SQL_FILE: ${CBIOPORTAL_SEED_SQL_FILE}
    restart: always
    environment:
      BRANCH: ${CBIOPORTAL_BRANCH}
      SUBPATH: ${CBIOPORTAL_SUBPATH:-ROOT}
      DB_HOST: cbioportal-mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: &mysql_root_password letmein
      DB_NAME: &mysql_database cbioportal
      DO_DB_MIGRATE: ${DO_DB_MIGRATE:-no}
      MVN_GOALS: clean install
      FORCE_MVN_BUILD: ${FORCE_MVN_BUILD:-no}
    extra_hosts:
    - "civicdb.org:127.0.0.1"
    - "mutationassessor.org:127.0.0.1"
    volumes:
    - type: bind
      source: ./mountpoints/host
      target: /host
      read_only: false
    - type: bind
      source: ./mountpoints/mvn-repo
      target: /root/.m2/repository
      read_only: false
    - type: bind
      source: ./services/cbioportal/resources
      target: /resources
      read_only: false
    - type: bind
      source: ./services/cbioportal/context.xml
      target: /usr/local/tomcat/conf/context.xml
      read_only: true
    - type: bind
      source: ./services/cbioportal/server.xml
      target: /usr/local/tomcat/conf/server.xml
      read_only: true
    - type: bind
      source: ."${CBIOPORTAL_EXTERNAL_DATA}"
      target: /data/cbioportal
      read_only: false
    - type: bind
      source: /data/dfci/cbioone
      target: /cbioone
    - type: bind
      source: /data/dfci/cbioone/data/profile_latest.tar.gz
      target: /usr/local/tomcat/webapps/cbioportal/profile_latest.tar.gz
      bind:
          propagation: shared
      read_only: false
    depends_on:
    - cbioportal-mysql
    - oncokb
    - genome-nexus
    - session-service
    links:
    - cbioportal-mysql
    - oncokb
    - genome-nexus
    - session-service
    networks:
      cbio-bridge:
        ipv4_address: ${CBIOPORTAL_IPV4_ADDR}
      cbio-internal:
  cbioportal-mysql:
    image: cbioportal-cloud-cbioportal-mysql:latest
    build:
      context: services/cbioportal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: *mysql_root_password
      MYSQL_DATABASE: *mysql_database
    restart: always
    volumes:
    - type: bind
      source: ./mountpoints/host
      target: /host
      read_only: false
    - type: bind
      source: ./services/cbioportal-mysql/custom.cnf
      target: /etc/mysql/conf.d/custom.cnf
      read_only: true
    - type: bind
      source: ./mountpoints/cbioportal-mysql-data
      target: /var/lib/mysql
      read_only: false
    command: --ssl=0
    ports:
        - "3309:3306"
    networks:
      cbio-bridge:
        ipv4_address: ${CBIOPORTAL_MYSQL_IPV4_ADDR}
  oncokb:
    image: cbioportal-cloud-oncokb:latest
    build:
      context: services/oncokb
      args:
        BRANCH: ${ONCOKB_BRANCH}
        DB_HOST: oncokb-mysql
        DB_PORT: "3306"
        DB_USER: root
        DB_PASSWORD: letmein
        DB_NAME: oncokb
    restart: always
    depends_on:
    - oncokb-mysql
    links:
    - oncokb-mysql
    networks:
    - cbio-internal
  oncokb-mysql:
    image: cbioportal-cloud-oncokb-mysql:latest
    build:
      context: services/oncokb-mysql
      args:
        BRANCH: ${ONCOKB_BRANCH}
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: oncokb
    restart: always
    networks:
    - cbio-internal
  genome-nexus:
    image: cbioportal-cloud-genome-nexus:latest
    build:
      context: services/genome-nexus
      args:
        BRANCH: ${GENOME_NEXUS_BRANCH}
    environment:
      GN_MONGO_HOST: genome-nexus-mongodb
      GN_MONGO_PORT: "27017"
      GN_MONGO_NAME: annotator
      SERVER_PORT: 8888
    depends_on:
    - genome-nexus-mongodb
    links:
    - genome-nexus-mongodb
    restart: always
    networks:
    - cbio-internal
  genome-nexus-mongodb:
    image: cbioportal-cloud-genome-nexus-mongodb:latest
    build:
      context: services/genome-nexus-mongodb
      args:
        BRANCH: ${GENOME_NEXUS_MONGODB_BRANCH}
    restart: always
    networks:
    - cbio-internal
  session-service:
    image: cbioportal-cloud-session-service:latest
    build:
      context: services/session-service
      args:
        BRANCH: ${SESSION_SERVICE_BRANCH}
    environment:
      SS_MONGO_HOST: session-service-mongodb
      SS_MONGO_PORT: "27017"
      SS_MONGO_NAME: session-service
      SERVER_PORT: "8090"
    depends_on:
    - session-service-mongodb
    links:
    - session-service-mongodb
    restart: always
    networks:
    - cbio-internal
  session-service-mongodb:
    image: cbioportal-cloud-session-service-mongodb:latest
    build:
      context: services/session-service-mongodb
    restart: always
    networks:
    - cbio-internal
    volumes:
    - type: bind
      source: ./mountpoints/session-service-mongodb-data
      target: /data/db
      read_only: false
  genome-nexus-vep-old:
    image: cbioportal-cloud-genome-nexus-vep:latest
    build:
      context: services/genome-nexus-vep
      args:
        BRANCH: ${GENOME_NEXUS_VEP_BRANCH}
    restart: always
    networks: 
    - cbio-internal
    ports:
      - "8090:8080"  
    environment:
      VEP_CACHE: /opt/vep/.vep
      VEP_ASSEMBLY: GRCh37
    volumes:
    - type: bind
      source: ./mountpoints/genome-nexus-vep-cache
      target: /opt/vep/.vep
      read_only: true
  genome-nexus-vep:
    image: genomenexus/gn-vep:27223ebc69be55f8d6b31b9111c697ff7b2c0850
    restart: always
    networks: 
    - cbio-internal
    - cbio-bridge
    ports:
      - "8090:8080"  
    environment:
      VEP_CACHE: /opt/vep/.vep
      VEP_ASSEMBLY: GRCh37
    volumes:
    - type: bind
      source: ./mountpoints/genome-nexus-vep-cache
      target: /opt/vep/.vep
      read_only: true
  import-pipeline:
    build:
      context: services/import-pipeline
    environment:
      ACCESS_TOKEN: ${DROPBOX_ACCESS_TOKEN}
      ALLOWED_FOLDER: ${DROPBOX_ALLOWED_FOLDERS}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
      PORTAL_HOME: /host/cbioportal
      DOWNLOAD_DIR: /importer/files
      DB_LOCATION: /importer/main.db
      STUDY_LINK_DIR: /study_link_dir
      SCHEMA_SQL_PATH: /schema.sql
      DISABLE_USER_SYNC: ${IMPORT_PIPELINE_DISABLE_USER_SYNC}
      DISABLE_UNAUTH: ${IMPORT_PIPELINE_DISABLE_UNAUTH}
      DB_HOST: cbioportal-mysql
      DB_NAME: *mysql_database
      DB_USER: root
      DB_PASSWORD: *mysql_root_password
      GCLOUD_CREDS: ${GCLOUD_CREDS}
      AUTH_SHEET_KEY: ${AUTH_SHEET_KEY}
      AUTH_SHEET_WORKSHEET_NAME: ${AUTH_SHEET_WORKSHEET_NAME}
      AUTH_SHEET_KEYMAP: ${AUTH_SHEET_KEYMAP}
      AUTH_SHEET_TRUEVAL: ${AUTH_SHEET_TRUEVAL}
    volumes:
    - type: bind
      source: ./mountpoints/host
      target: /host
      read_only: false
    - type: bind
      source: ./mountpoints/importer
      target: /importer
      read_only: false
    - type: bind
      source: ./mountpoints/dashboard
      target: /dashboard
      read_only: false
    - type: bind
      source: ./services/import-pipeline/schema.sql
      target: /schema.sql
      read_only: true
    - type: bind
      source: ./services/import-pipeline/import_service
      target: /importer/import_service
      read_only: true
    networks:
    - cbio-bridge
    - cbio-internal
    links:
    - cbioportal
    - cbioportal-mysql

networks:
  cbio-internal:
    internal: true
    driver: bridge
  cbio-bridge:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET}

