version: "3"
services:
  cbioportal:
    image: cbioportal-local:latest
    build:
      context: ./cbioportal
      args:
        BRANCH: master
        JDBC_DRIVER: com.mysql.jdbc.Driver
        DB_HOST: 192.168.0.1
        DB_PORT: "3306"
        DB_USER: root
        DB_PASSWORD: letmein
        DB_NAME: cbioportal
    ports:
    - "8080:8080"
    restart: always
    networks:
      cbio-bridge:
        - ipv4_address: 192.187.10.1

  oncokb:
    image: oncokb-local:latest
    build:
      context: ./oncokb
      args:
        BRANCH: v0.3.2
        DB_HOST: oncokb-mysql
        DB_PORT: "3306"
        DB_USER: root
        DB_PASSWORD: letmein
        DB_NAME: oncokb
    restart: always
    networks:
      cbio-bridge:
  oncokb-mysql:
    image: oncokb-mysql-local:latest
    build:
      context: oncokb-mysql
      args:
        BRANCH: v0.3.2
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: oncokb
    networks:
      cbio-bridge:
  genome-nexus:
    image: genome-nexus-local:latest
    build:
      context: ./genome-nexus
      args:
        BRANCH: master
    environment:
      GN_MONGO_HOST: genome-nexus-mongodb
      GN_MONGO_PORT: "27017"
      GN_MONGO_NAME: annotator
      SERVER_PORT: 8888
    links:
    - genome-nexus-mongodb
    depends_on:
    - genome-nexus-mongodb
    restart: always
    networks:
      cbio-bridge:
  genome-nexus-mongodb:
    build: https://github.com/genome-nexus/genome-nexus-importer.git#v0.4
    restart: always
    networks:
      cbio-bridge:
  session-service:
    image: session-service-local:latest
    build:
      context: ./session-service
      args:
        BRANCH: master
    environment:
      SS_MONGO_HOST: session-service-mongodb
      SS_MONGO_PORT: "27017"
      SS_MONGO_NAME: session-service
      SERVER_PORT: "8090"
    depends_on:
    - session-service-mongodb
    links:
    - session-service-mongodb
    restart: always
    networks:
      cbio-bridge:
  session-service-mongodb:
    image: mongo:3.6.2
    restart: always
    networks:
      cbio-bridge:


networks:
  cbio-bridge:
    external: true
