version: "3.2"
services:
  nginx-wrapper:
    image: cbioportal-cloud-nginx-wrapper:latest
    build:
      context: ./nginx-wrapper
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - type: bind
      source: ./nginx-wrapper/nginx.conf
      target: /etc/nginx/conf.d/default.conf
      read_only: true
    - type: bind
      source: ./nginx-wrapper/cert.crt
      target: /etc/nginx/cert.crt
      read_only: true
    - type: bind
      source: ./nginx-wrapper/cert.key
      target: /etc/nginx/cert.key
      read_only: true
    depends_on:
    - cbioportal
    links:
    - cbioportal
    networks:
    - cbio-bridge
  cbioportal:
    image: cbioportal-cloud:latest
    build:
      context: ./cbioportal
      args:
        BRANCH: master
        DB_HOST: cbioportal-mysql
        DB_PORT: "3306"
        DB_USER: root
        DB_PASSWORD: &mysql_root_password letmein
        DB_NAME: &mysql_database cbioportal
    restart: always
    volumes:
    - type: bind
      source: ./host
      target: /host
      read_only: false
    - type: bind
      source: ./cbioportal/context.xml
      target: /usr/local/tomcat/cont/context.xml
      read_only: true
    depends_on:
    - cbioportal-mysql
    - oncokb
    - genome-nexus
    - session-service
    links:
    - cbioportal-mysql
    - oncokb
    - genome-nexus
    - session-service
    networks:
      cbio-bridge:
        ipv4_address: 172.28.10.10
  cbioportal-mysql:
    image: cbioportal-cloud-cbioportal-mysql:latest
    build:
      context: ./cbioportal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: *mysql_root_password
      MYSQL_DATABASE: *mysql_database
    restart: always
    volumes:
    - type: bind
      source: ./host
      target: /host
      read_only: false
    - type: bind
      source: ./cbioportal-mysql/custom.cnf
      target: ./etc/mysql/conf.d/custom.cnf
      read_only: true
    - type: bind
      source: ./cbioportal-mysql/mysql-data
      target: /var/lib/mysql
      read_only: false
    networks:
      cbio-bridge:
        ipv4_address: 172.28.10.11
  oncokb:
    image: cbioportal-cloud-oncokb:latest
    build:
      context: ./oncokb
      args:
        BRANCH: v0.3.2
        DB_HOST: oncokb-mysql
        DB_PORT: "3306"
        DB_USER: root
        DB_PASSWORD: letmein
        DB_NAME: oncokb
    restart: always
    depends_on:
    - oncokb-mysql
    links:
    - oncokb-mysql
    networks:
    - cbio-bridge
  oncokb-mysql:
    image: cbioportal-cloud-oncokb-mysql:latest
    build:
      context: oncokb-mysql
      args:
        BRANCH: v0.3.2
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: oncokb
    restart: always
    networks:
    - cbio-bridge
  genome-nexus:
    image: cbioportal-cloud-genome-nexus:latest
    build:
      context: ./genome-nexus
      args:
        BRANCH: master
    environment:
      GN_MONGO_HOST: genome-nexus-mongodb
      GN_MONGO_PORT: "27017"
      GN_MONGO_NAME: annotator
      SERVER_PORT: 8888
    depends_on:
    - genome-nexus-mongodb
    links:
    - genome-nexus-mongodb
    restart: always
    networks:
    - cbio-bridge
  genome-nexus-mongodb:
    image: cbioportal-cloud-genome-nexus-mongodb:latest
    build:
      context: ./genome-nexus-mongodb
      args:
        BRANCH: v0.4
    restart: always
    networks:
    - cbio-bridge
  session-service:
    image: cbioportal-cloud-session-service:latest
    build:
      context: ./session-service
      args:
        BRANCH: master
    environment:
      SS_MONGO_HOST: session-service-mongodb
      SS_MONGO_PORT: "27017"
      SS_MONGO_NAME: session-service
      SERVER_PORT: "8090"
    depends_on:
    - session-service-mongodb
    links:
    - session-service-mongodb
    restart: always
    networks:
    - cbio-bridge
  session-service-mongodb:
    image: cbioportal-cloud-session-service-mongodb:latest
    build:
      context: ./session-service-mongodb
    restart: always
    networks:
    - cbio-bridge
  cancerhotspots:
    image: cbioportal-cloud-cancerhotspots:latest
    build:
      context: ./cancerhotspots
      args:
        BRANCH: master
    restart: always
    networks:
    - cbio-bridge

networks:
  cbio-bridge:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.28.10.0/24"

