version: "3.2"
services:
  nginx-wrapper:
    image: cbioportal-cloud-nginx-wrapper:latest
    build:
      context: services/nginx-wrapper
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - type: bind
      source: ./services/nginx-wrapper/nginx.conf
      target: /etc/nginx/conf.d/default.conf
      read_only: true
    - type: bind
      source: ./mountpoints/nginx-wrapper/cert.crt
      target: /etc/nginx/cert.crt
      read_only: true
    - type: bind
      source: ./mountpoints/nginx-wrapper/cert.key
      target: /etc/nginx/cert.key
      read_only: true
    - type: bind
      source: ./mountpoints/dashboard/
      target: /etc/nginx/html/dashboard
      read_only: true
    depends_on:
    - cbioportal
    links:
    - cbioportal
    networks:
    - cbio-bridge
  cbioportal:
    image: cbioportal-cloud:latest
    build:
      context: services/cbioportal
    restart: always
    environment:
      BRANCH: master
      DB_HOST: cbioportal-mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: &mysql_root_password letmein
      DB_NAME: &mysql_database cbioportal
      DO_DB_MIGRATE: ${DO_DB_MIGRATE:-no}
      MVN_GOALS: clean install
      FORCE_MVN_BUILD: ${FORCE_MVN_BUILD:-no}
    volumes:
    - type: bind
      source: ./mountpoints/host
      target: /host
      read_only: false
    - type: bind
      source: ./mountpoints/mvn-repo
      target: /root/.m2/repository
      read_only: false
    - type: bind
      source: ./services/cbioportal/resources
      target: /resources
      read_only: false
    - type: bind
      source: ./services/cbioportal/context.xml
      target: /usr/local/tomcat/conf/context.xml
      read_only: true
    - type: bind
      source: ./services/cbioportal/server.xml
      target: /usr/local/tomcat/conf/server.xml
      read_only: true
    depends_on:
    - cbioportal-mysql
    - oncokb
    - genome-nexus
    - session-service
    links:
    - cbioportal-mysql
    - oncokb
    - genome-nexus
    - session-service
    networks:
      cbio-bridge:
        ipv4_address: 172.28.10.11
  cbioportal-mysql:
    image: cbioportal-cloud-cbioportal-mysql:latest
    build:
      context: services/cbioportal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: *mysql_root_password
      MYSQL_DATABASE: *mysql_database
    restart: always
    volumes:
    - type: bind
      source: ./mountpoints/host
      target: /host
      read_only: false
    - type: bind
      source: ./services/cbioportal-mysql/custom.cnf
      target: /etc/mysql/conf.d/custom.cnf
      read_only: true
    - type: bind
      source: ./mountpoints/cbioportal-mysql-data
      target: /var/lib/mysql
      read_only: false
    networks:
      cbio-bridge:
        ipv4_address: 172.28.10.12
  oncokb:
    image: cbioportal-cloud-oncokb:latest
    build:
      context: services/oncokb
      args:
        BRANCH: &oncokb_branch v0.3.1
        DB_HOST: oncokb-mysql
        DB_PORT: "3306"
        DB_USER: root
        DB_PASSWORD: letmein
        DB_NAME: oncokb
    restart: always
    depends_on:
    - oncokb-mysql
    links:
    - oncokb-mysql
    networks:
    - cbio-bridge
  oncokb-mysql:
    image: cbioportal-cloud-oncokb-mysql:latest
    build:
      context: services/oncokb-mysql
      args:
        BRANCH: *oncokb_branch
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: oncokb
    restart: always
    networks:
    - cbio-bridge
  genome-nexus:
    image: cbioportal-cloud-genome-nexus:latest
    build:
      context: services/genome-nexus
      args:
        BRANCH: master
    environment:
      GN_MONGO_HOST: genome-nexus-mongodb
      GN_MONGO_PORT: "27017"
      GN_MONGO_NAME: annotator
      SERVER_PORT: 8888
    depends_on:
    - genome-nexus-mongodb
    links:
    - genome-nexus-mongodb
    restart: always
    networks:
    - cbio-bridge
  genome-nexus-mongodb:
    image: cbioportal-cloud-genome-nexus-mongodb:latest
    build:
      context: services/genome-nexus-mongodb
      args:
        BRANCH: v0.4
    restart: always
    networks:
    - cbio-bridge
  session-service:
    image: cbioportal-cloud-session-service:latest
    build:
      context: services/session-service
      args:
        BRANCH: master
    environment:
      SS_MONGO_HOST: session-service-mongodb
      SS_MONGO_PORT: "27017"
      SS_MONGO_NAME: session-service
      SERVER_PORT: "8090"
    depends_on:
    - session-service-mongodb
    links:
    - session-service-mongodb
    restart: always
    networks:
    - cbio-bridge
  session-service-mongodb:
    image: cbioportal-cloud-session-service-mongodb:latest
    build:
      context: services/session-service-mongodb
    restart: always
    networks:
    - cbio-bridge
  cancerhotspots:
    image: cbioportal-cloud-cancerhotspots:latest
    build:
      context: services/cancerhotspots
      args:
        BRANCH: master
    restart: always
    networks:
    - cbio-bridge
  import-pipeline:
    build:
      context: services/import-pipeline
    environment:
      ACCESS_TOKEN: ${DROPBOX_ACCESS_TOKEN}
      ALLOWED_FOLDER: ${DROPBOX_ALLOWED_FOLDERS}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
      PORTAL_HOME: /host/cbioportal
      DOWNLOAD_DIR: /importer/files
      DB_LOCATION: /importer/main.db
      STUDY_LINK_DIR: /study_link_dir
      SCHEMA_SQL_PATH: /schema.sql
      DB_HOST: cbioportal-mysql
      DB_NAME: *mysql_database
      DB_USER: root
      DB_PASSWORD: *mysql_root_password
    volumes:
    - type: bind
      source: ./mountpoints/host
      target: /host
      read_only: false
    - type: bind
      source: ./mountpoints/importer
      target: /importer
      read_only: false
    - type: bind
      source: ./mountpoints/dashboard
      target: /dashboard
      read_only: false
    - type: bind
      source: ./services/import-pipeline/schema.sql
      target: /schema.sql
      read_only: true
    - type: bind
      source: ./services/import-pipeline/import_service
      target: /importer/import_service
      read_only: true
    networks:
    - cbio-bridge
    depends_on:
    - cbioportal
    - cbioportal-mysql
    links:
    - cbioportal
    - cbioportal-mysql

networks:
  cbio-bridge:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.28.10.0/24"

